"""add tracking logs (weight, water, food, exercise)

Revision ID: 511e22eda60e
Revises: 7cec25a080fd
Create Date: 2026-07-05 00:37:39.902698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511e22eda60e'
down_revision: Union[str, Sequence[str], None] = '7cec25a080fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('exercise', sa.String(length=100), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('met', sa.Float(), nullable=False),
    sa.Column('calories_burned_kcal', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_logs'))
    )
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.create_index('ix_exercise_logs_user_logged_at', ['user_id', 'logged_at'], unique=False)

    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('meal', sa.String(length=16), nullable=True),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_food_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_logs'))
    )
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.create_index('ix_food_logs_user_logged_at', ['user_id', 'logged_at'], unique=False)

    op.create_table('water_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('volume_ml', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_water_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_logs'))
    )
    with op.batch_alter_table('water_logs', schema=None) as batch_op:
        batch_op.create_index('ix_water_logs_user_logged_at', ['user_id', 'logged_at'], unique=False)

    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weight_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_logs'))
    )
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.create_index('ix_weight_logs_user_logged_at', ['user_id', 'logged_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_weight_logs_user_logged_at')

    op.drop_table('weight_logs')
    with op.batch_alter_table('water_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_water_logs_user_logged_at')

    op.drop_table('water_logs')
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_food_logs_user_logged_at')

    op.drop_table('food_logs')
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_exercise_logs_user_logged_at')

    op.drop_table('exercise_logs')
    # ### end Alembic commands ###
